name = "blackroad-tools"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "blackroad-continuity"
database_id = "f0721506-cb52-41ee-b587-38f7b42b97d9"

[[kv_namespaces]]
binding = "TOOLS_KV"
id = "f7b2b20d1e1447b2917b781e6ab7e45c"

[observability]
enabled = true
